### ISSUE TITLE
[PickableTimeFixMod] Limited to Windows Clients

### ISSUE THREAD

**Issue by arcayr** [pipakin/PipakinsMods#1]
Hello,

The following line in the mod prevents this being used on non-Windows systems:

https://github.com/pipakin/PipakinsMods/blob/c56e314c94ee5f6d183ecffa9180763adb8ce82e/PickableTimeFixMod/PickableTimeFixMod.cs#L7

Is there any reason why it's there other than as part of testing? I wanted to see if the mod worked server-side too but my server runs Linux.

Cheers,

A

**Comment by pipakin** [comment]
Nope, other than my noobishness to bepinex. I'm releasing a new version without that line now.
